name: Render Wake-up

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    environment: WAKE_UP
    
    steps:
      - name: Send Ping to Render WebSocket
        run: |
          pip install websocket-client --quiet --no-cache-dir
          python -c "
import websocket
import ssl
import os

url = os.environ.get('RENDER_URL')
try:
    ws = websocket.create_connection(url, timeout=3, sslopt={'cert_reqs': ssl.CERT_NONE}) 
    ws.close()
except:
    pass
" || true
        
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
