name: Render Wake Up

on:
  schedule:
    - cron: '*/13 * * * *'
  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    environment: Render
    steps:
    
      - name: Send request to Render 1
        run: curl -I --fail "${{ secrets.RENDER_URL_1 }}"
