name: Render Wake-up

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    environment: WAKE_UP
    steps:
      - name: Send Ping to Render Web Service
        run: |
          curl -sS "${{ secrets.RENDER_URL }}"
