name: Render Wake-up

on:
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    environment: WAKE_UP

    steps:
      - name: 1. Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: 2. Install wscat
        run: npm install -g wscat
        
      - name: 3. Send Ping to Render WebSocket
        run: wscat -c "${{ secrets.RENDER_URL }}"
