name: Render Wake Up

on:
  workflow_dispatch:

  schedule:
    - cron: '*/13 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: WAKE_UP

    steps:
      - name: Send request to Render
        run: curl -s -o /dev/null --fail "${{ secrets.RENDER_URL }}"
