name: Supabase Wake-up

on:
  schedule:
    - cron: '0 9 * * 1,4'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    environment: Supabase
    steps:
      - name: Send request to Supabase 1
        run: |
          curl --request GET --header "apikey: ${{ secrets.SUPABASE_API_KEY_1 }}" --header "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY_1 }}" "${{ secrets.SUPABASE_URL_1 }}/rest/v1/ping?limit=1"
