name: Supabase Wake-up

on:
  schedule:
    - cron: '0 9 * * 1,4'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Supabase API
        run: |
          curl --request GET --header "apikey: ${{ secrets.SUPABASE_API_KEY }}" --header "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}" "${{ secrets.SUPABASE_URL }}/rest/v1/ping?limit=1"
